repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
        language_version: python3
      - id: check-toml
      - id: check-yaml
      - id: fix-encoding-pragma
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, master]
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check
        language: python
        language_version: python3
-   repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.7.0
    hooks:
    - id: blacken-docs
-   repo: git://github.com/doublify/pre-commit-isort
    rev: v4.3.0
    hooks:
    -   id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    -   id: flake8
